On Error Resume Next
Set WshNetwork = CreateObject("WScript.Network")
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\4050b"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\AccountingSharp"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\AD - SHARP Fax"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\ADPrinter - Black"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\ADPrinter - Color"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice4 - Black"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice4 - Color"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice4 - Sharp Fax"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice1-HP4050A"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\CertificatePrinter"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\DellColorLaser"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice3 - Black"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice3 - HP Color CP4005-PCL6"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice2 - Black"
WshNetwork.AddWindowsPrinterConnection "\\10.0.0.22\BranchOffice2 - Color"